export {nameSchema} from "./name-schema"
export {integerSchema} from "./integerSchema"
export {numberSchema} from "./numberSchema"
export {dateSchema} from "./dateSchema"
export {priceSchema} from "./price-schema"
export {documentSchema} from "./documentSchema"
export {petSchema} from "./petSchema"
export {phoneSchema} from "./phone-schema"
